"""second migigrations

Revision ID: 01663bb4b45d
Revises: 068a6e95880f
Create Date: 2025-10-12 06:42:53.130177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01663bb4b45d'
down_revision: Union[str, Sequence[str], None] = '068a6e95880f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolist_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('owner', 'viewer', 'editor', name='role_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['todolist.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['todolist_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todolist_task', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todolist_task', 'todolist_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todolist_task', type_='foreignkey')
    op.drop_column('todolist_task', 'user_id')
    op.drop_table('todolist_members')
    # ### end Alembic commands ###
